### PR TITLE
Created module to install AWS memcached plugin

### PR DESCRIPTION
**Pull request by iuriaranda**
Take into account that this is just preliminary work, I'm still testing this in my vagrant box. But I just wanted to hear your thoughts on this.

### CODE REVIEW

**Comment by iuriaranda** [comment]
Testing this with vagrant, I'm facing the issue that the plugin .tgz file is not being correctly transfered from the puppet module to the machine [here](https://github.com/skyscrapers/puppet-memcached/pull/3/files#diff-0d72ac1126b5c1b5190821c5c7e13f7cR35), so the `pecl install` command exits with this error: 

```
==> 1404: Notice: /Stage[main]/Memcached::Aws_php_plugin/Exec[pecl_install_memcached]/returns: Could not get contents of package "/tmp/AwsElasticCacheClusterClient.tgz". Invalid tgz file.
```

**Comment by iuriaranda** [comment]
Now I only need to add the memcached plugin packages for all PHP versions

**Comment by iuriaranda** [comment]
Now testing with different php versions in vagrant

**Comment by venturel** [comment]
+1

**Comment by MattiasGees** [comment]
👍

**Pull request merged**
